### ISSUE TITLE
シャントの配線があまりよろしくない

### ISSUE THREAD

**Issue by TakashiKusachi** [hayate2718/bl_motor_d#6]
## 低抵抗シャントでの電流測定の配線があまりよろしくない
低抵抗の電流計測はアナログ回路としてかなり丁寧に設計しないと実はろくに使えたものじゃないので注意してください。

### 抵抗器と分岐点の間にできるだけ電流を流さないこと
電流測定に重要なことは信用できる抵抗値であり、これを達成するにはパターンの抵抗自体考慮する必要があります。このため下図のように、電流が流れるルートから切り離して測定用のパターンを伸ばす必要があります。
少し話は変わってしまいますが、４端子抵抗測定法などを調べてみると勉強になるかも
![shant](https://user-images.githubusercontent.com/26002398/94586874-c0ff5c00-02bc-11eb-83c8-e3ff3138bccc.PNG)
![shant2](https://user-images.githubusercontent.com/26002398/94587108-16d40400-02bd-11eb-83dc-8061e25ee984.PNG)
この距離が良くないという話。
### ただし、そもそも抵抗器が5%...
なので気にしなくてもいいかも。

## 配線の長さをそろえる部分について
多分いらない。配線の長さをそろえるのは、主にデジタルの高速信号の場合だけです。配線長の偏差が信号の周期の定数倍以上になると周期がずれて信号が正確に読み取れなくなりますが、アナログで低速である限りは必要ないです。
また、上の話を考慮したくなるかもしれないですが、この信号線に流れる電流は微量（入力インピーダンスが高い）です。なので、配線の長さをそろえてインピーダンスをそろえる必要はないです。一方で電流が小さいからこそ、ノイズに弱い信号線になります。下手にくねくねさせた方が危ない。

**Comment by TakashiKusachi** [comment]
追記。データシートにながさ揃えろって書いてあるのか…
こんな露骨にくねくねさせるよりは、自然に長さがそろうようにした方がいいかと。図のような配線なら勝手に合うはず

**Comment by hayate2718** [comment]
測定点までの距離を同じくらいにするために0Ω抵抗を使って測定用の配線を作ってみます。くねくねさせて無理やりそろえるくらいだったら多少の誤差は無視したほうが良いですか？

**Comment by TakashiKusachi** [comment]
0オーム？

多少はね。無視してもいいんじゃないかな
